apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-db
  namespace: kubenews
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: kube-postgre
        image: postgres:15.0
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: "kubenews"
          - name: POSTGRES_USER
            value: "kubenews"
          - name: POSTGRES_PASSWORD
            value: "Pg#321"
