apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-app
  namespace: kubenews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: kube-app
        image: erivaldolopes/kube-news:{{TAG}}
        ports:
        - containerPort: 8080
        env:
          - name: DB_DATABASE
            value: "kubenews"
          - name: DB_USERNAME
            value: "kubenews"
          - name: DB_PASSWORD
            value: "Pg#321"
          - name: DB_HOST
            value: "kube-db"