apiVersion: v1
kind: Service
metadata:
  name: kube-app
  namespace: kubenews
spec:
  selector:
    app: app
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  type: NodePort